name: Publish Docker Container

on:
  push:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push the Docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.SECRET_LAYOUT }}
        run: |
          docker buildx build . --tag ghcr.io/CrysG011/LayoutBase-v2:latest --push

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          repo_token: ${{ secrets.SECRET_LAYOUT }}
          publish_dir: ./public
